apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJjcmVkc1N0b3JlIjogImRlc2t0b3AiLAogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJhV3hwWVMxaWRYUnZkbk5yYVdrNloyaHdYM0pFVVU1VFkybFlPR1l4VEdWVmNHeG9iMUYyWjBwWFVFTnlVVkZQTlRCVWFUSllaQT09IgogICAgfQogIH0KfQo=
type: kubernetes.io/dockerconfigjson
